version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-2.0
jobs:  
  test-2.0:
    docker:
      - image: microsoft/dotnet:2.0-sdk-jessie
    steps:
      - run:
          name: install packages
          command: apt-get -q update && apt-get install -qy awscli
      - checkout
      - run: aws s3 cp s3://launchdarkly-pastebin/ci/dotnet/LaunchDarkly.Xamarin.snk LaunchDarkly.Xamarin.snk
      - run: dotnet restore
      - run: dotnet build src/LaunchDarkly.Xamarin -f netstandard2.0
      - run: dotnet test tests/LaunchDarkly.Xamarin.Tests/LaunchDarkly.Xamarin.Tests.csproj -f netcoreapp2.0
