apiVersion: apps/v1
kind: Deployment
metadata:
  name: ezkonnect-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ezkonnect-server
  template:
    metadata:
      labels:
        app: ezkonnect-server
    spec:
      containers:
        - name: ezkonnect-server
          image: yotamloe/ezkonnect-server:0.0.1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ezkonnect-server
spec:
  selector:
    app: ezkonnect-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ezkonnect-server
rules:
  - apiGroups:
      - ""
      - logz.io
    resources:
      - pods
      - services
      - instrumentedapplications
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ezkonnect-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ezkonnect-server
subjects:
  - kind: ServiceAccount
    name: default
    # TODO: Change this to the namespace where you deployed the service
    namespace: default
