apiVersion: apps/v1
kind: Deployment
metadata:
  name: easy-connect-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easy-connect-server
  template:
    metadata:
      labels:
        app: easy-connect-server
    spec:
      containers:
        - name: easy-connect-server
          securityContext:
            capabilities:
              drop:
                - all
          image: logzio/easy-connect-server:v1.0.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: easy-connect-server
spec:
  selector:
    app: easy-connect-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: easy-connect-server
rules:
  - apiGroups:
      - ""
      - logz.io
    resources:
      - pods
      - services
      - instrumentedapplications
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: easy-connect-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: easy-connect-server
subjects:
  - kind: ServiceAccount
    name: default
    # TODO: Change this to the namespace where you deployed the service
    namespace: default
