repo:
  public: dotnet-client-sdk
  private: dotnet-client-sdk-private

circleci:
  mac:
    xcode: "12.4.0"
  windows:  # only for building documentation
    env:
      LD_RELEASE_DOCS_TARGET_FRAMEWORK: netstandard2.0
      LD_RELEASE_DOCS_ASSEMBLIES: LaunchDarkly.ClientSdk LaunchDarkly.CommonSdk
    steps:
      - step: build
      - step: build-docs
      - step: publish-docs

template:
  name: dotnet-windows  # only for building documentation

publications:
  - url: https://www.nuget.org/packages/LaunchDarkly.ClientSdk
    description: NuGet

documentation:
  title: LaunchDarkly Client-Side SDK for .NET
  githubPages: true

sdk:
  displayName: ".NET (client-side)"
