repo:
  public: xamarin-client-sdk
  private: xamarin-client-sdk-private

circleci:
  mac:
    xcode: "12.4.0"
  windows:  # only for building documentation
    env:
      LD_RELEASE_DOCS_TARGET_FRAMEWORK: netstandard2.0
      LD_RELEASE_DOCS_ASSEMBLIES: LaunchDarkly.XamarinSdk LaunchDarkly.CommonSdk
    steps:
      - step: build
      - step: build-docs
      - step: publish-docs

releasableBranches:
  - name: master
    description: 2.x
  - name: 1.x

template:
  name: dotnet-windows  # only for building documentation

publications:
  - url: https://www.nuget.org/packages/LaunchDarkly.XamarinSdk
    description: NuGet

documentation:
  title: LaunchDarkly Client-Side SDK for Xamarin
  githubPages: true

sdk:
  displayName: "Xamarin"
