name: RIT Action Continuous Integration Test

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
env:
  TEST_TAG:  ${{ github.event.repository.name }}/rit:test
  LATEST_TAG: ghcr.io/rsksmart/${{ github.event.repository.name }}/rit

jobs:
  build-push-rit-action-image:
    name: Test  RIT Action docker image
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.LATEST_TAG }}
            ${{ env.TEST_TAG }}

      - name: Setup Docker BuildX
        id: setup-buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: network=host
          platforms: linux/amd64

      - name: Build and export locally Docker
        uses: docker/build-push-action@v6
        with:
          context: .github/images
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Test the RIT Container Action
        id: test-container
        run: |
          docker run  \
            --env INPUT_RSKJ_BRANCH="master" \
            --env INPUT_POWPEG_NODE_BRANCH="master" \
            --env INPUT_RIT_BRANCH="main" \
            --env INPUT_RIT_LOG_LEVEL="info" \
            --env "GITHUB_OUTPUT=/github-output" \
            -v "$GITHUB_OUTPUT:/github-output" \
            --rm ${{ env.TEST_TAG }}

      - name: GitHub container registry login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the RIT Action Container Image
        uses: docker/build-push-action@v6
        with:
          context: .github/images
          tags: ${{ env.LATEST_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
          load: true
          push: true

  test-rit-action:
    needs:  build-push-rit-action-image
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: GitHub container registry login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Test RIT Action
        id: test-rit-action
        uses: docker://ghcr.io/rsksmart/rootstock-integration-tests/rit:latest
        with:
          rskj-branch: master
          powpeg-node-branch: master

      - name: Print RIT Status and Message
        id: output
        run: |
          echo "RIT Status = ${{ steps.test-rit-action.outputs.status }}"
          echo "RIT Message = ${{ steps.test-rit-action.outputs.message }}"
